services:
  #  nginx: 
  #    build:
  #      context: .
  #      dockerfile: docker/local.env/nginx/Dockerfile
  #      networks: 
  #        - default
  #      ports: 
  #         - 8010:80
  practice-web-app:
    build:
      context: .
      docker: ./docker/local.env/php-laravel/Dockerfile
    networks:
      - default
