services:
  cms-web-app:
    build:
      context: .
      dockerfile: ./practice-cms/docker/local.env/php-laravel/Dockerfile
    volumes:
      - ./practice-cms/:/work/backend
      - ./practice-cms/docker/local.env/php-laravel/php.ini:/usr/local/etc/php.ini 
      - ./practice-cms/docker/local.env/php-laravel/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
    networks:
      - default
  cms-nginx: 
    build:
    context: .
    dockerfile: ./practice-cms/docker/local.env/nginx/Dockerfile
    networks: 
      - default
    ports: 
      - 8010:80
