services:
  practice-web-app:
    build:
      context: .
      dockerfile: ./practice-cms/docker/local.env/php-laravel/Dockerfile
    volumes:
      - ./practice-cms/:/work/backend
    networks:
      - default
      #  nginx: 
  #    build:
  #      context: .
  #      dockerfile: ./practice-cms/docker/local.env/nginx/Dockerfile
  #      networks: 
  #        - default
  #      ports: 
  #         - 8010:80
